# Your Solution
services:
  book_catalog:
    image: book_catalog
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: catalog
    ports:
      - "8000:8000" 

  inventory_management:
    image: inventory
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory
    ports:
      - "8001:8001"