services:
  book_catalog:
    image: "${REGISTRY_HOSTNAME}/book_catalog:${VERSION}"
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: catalog
    ports:
      - "8000:8000" 
    environment:
      - DATABASE_URL=postgresql://library_5aya_user:95juShCQRCnURO4ICnHNixBa5hTEZjeC@dpg-crh8jm08fa8c738tn0bg-a.oregon-postgres.render.com/library_5aya

  inventory_management:
    image: "${REGISTRY_HOSTNAME}/inventory:${VERSION}"
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://library_5aya_user:95juShCQRCnURO4ICnHNixBa5hTEZjeC@dpg-crh8jm08fa8c738tn0bg-a.oregon-postgres.render.com/library_5aya