name: Deploy microservice

on:
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false
          
    - uses: actions/checkout@v3

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform

    - name: Set environment variables from Terraform outputs
      id: set_env
      run: |
          echo "REGISTRY_HOSTNAME=$(terraform output -raw registry_hostname)" >> $GITHUB_OUTPUT
          echo "REGISTRY_UN=$(terraform output -raw registry_un)" >> $GITHUB_OUTPUT
          echo "REGISTRY_PW=$(terraform output -raw registry_pw)" >> $GITHUB_OUTPUT
          echo "KUBE_CONFIG=$(echo -n $(terraform output -raw kube_config) | base64)" >> $GITHUB_OUTPUT
      working-directory: ./terraform

    - name: Setting permissions for build script
      run: chmod +x ./scripts/build-image.sh
      
    - name: Build
      run: ./scripts/build-image.sh

    - name: Setting permissions for push script
      run: chmod +x ./scripts/push-image.sh

    - name: Publish
      run: ./scripts/push-image.sh

    - uses: tale/kubectl-action@v1
      with:
        base64-kube-config: ${{steps.set_env.outputs.KUBE_CONFIG }}
        kubectl-version: v1.24.2

    - name: Setting permissions for deploy script
      run: chmod +x ./scripts/deploy.sh
      
    - name: Deploy
      run: ./scripts/deploy.sh
